# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [87]:
# Install pandas and numpy if the active Python environment does not have them. Using Python venv is recommended when you are doing so.
%pip install pandas numpy

Requirement already satisfied: pandas in /home/mark/projects/ctp_proj/ds-fall-2026/.venv/lib/python3.14/site-packages (3.0.5)
Requirement already satisfied: numpy in /home/mark/projects/ctp_proj/ds-fall-2026/.venv/lib/python3.14/site-packages (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/mark/projects/ctp_proj/ds-fall-2026/.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/mark/projects/ctp_proj/ds-fall-2026/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [88]:
# Import here.
import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

Load the Food choices data set into a new variable, `df_food`.

In [89]:
# Load the Food choices data set.

food_data_set_path = 'data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [90]:
# Count by hand. (lol kidding)
df_food.shape

(125, 61)

In [91]:
# Try to print or display it nicely.

df_food.head()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190

What are the columns and their types in this data set?

In [92]:
# Show the column names and their types.
df_food.info()

<class 'pandas.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           123 non-null    str
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  106 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  124 non-null    str
 8   comfort_food_reasons          123 non-null    str
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  124 non-null    str
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                122 non-null    str
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             122 non-null    str
 25  fav_cuisine                   123 non-null    str
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                124 non-null    str
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  124 non-null    str
 35  ideal_diet                    124 non-null    str
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           122 non-null    str
 43  mother_education              122 non-null    float64
 44  mother_profession             123 non-null    str
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   99 non-null     str
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        123 non-null    str
dtypes: float64(20), int64(27), str(14)
memory usage: 59.7 KB

In [93]:
pd.set_option("display.max_rows", 100) # Set pandas to render up to 100 rows first. Default caps to 10 and takes the middle chunk out to make the DataFrame fit.

# Try to display the column information as a nice pandas DataFrame.
df_food.dtypes.to_frame()

                                    0
GPA                               str
Gender                          int64
breakfast                       int64
calories_chicken                int64
calories_day                  float64
calories_scone                float64
coffee                          int64
comfort_food                      str
comfort_food_reasons              str
comfort_food_reasons_coded    float64
cook                          float64
comfort_food_reasons_coded.1    int64
cuisine                       float64
diet_current                      str
diet_current_coded              int64
drink                         float64
eating_changes                    str
eating_changes_coded            int64
eating_changes_coded1           int64
eating_out                      int64
employment                    float64
ethnic_food                     int64
exercise                      float64
father_education              float64
father_profession                 str
fav_cuisine                       str
fav_cuisine_coded               int64
fav_food                      float64
food_childhood                    str
fries                           int64
fruit_day                       int64
grade_level                     int64
greek_food                      int64
healthy_feeling                 int64
healthy_meal                      str
ideal_diet                        str
ideal_diet_coded                int64
income                        float64
indian_food                     int64
italian_food                    int64
life_rewarding                float64
marital_status                float64
meals_dinner_friend               str
mother_education              float64
mother_profession                 str
nutritional_check               int64
on_off_campus                 float64
parents_cook                    int64
pay_meal_out                    int64
persian_food                  float64
self_perception_weight        float64
soup                          float64
sports                        float64
thai_food                       int64
tortilla_calories             float64
turkey_calories                 int64
type_sports                       str
veggies_day                     int64
vitamins                        int64
waffle_calories                 int64
weight                            str

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns? (Assign the result to a new variable, `df_food_col_subset`.)

In [94]:
# Remove ‘em.
df_food_col_subset = df_food[['calories_day', 'weight', 'Gender']]

In [38]:
# Is there a second way to remove columns?
df_food_col_subset= df_food.drop(columns=['''I WONT FORGET TO DO THE LOOP HERE BEFORE SUBMITTT!!!!'''])

KeyError: "['I WONT FORGET TO DO THE LOOP HERE BEFORE SUBMITTT!!!!'] not found in axis"

In [95]:
# 🚀 Extra credit: What about a third way to remove columns?
df_food_col_subset = df_food.loc[:, ['calories_day','weight', 'Gender']]

What about `NaN`s? How many are there?

In [96]:
# Count ‘em.

df_food.isna().sum()

GPA                              2
Gender                           0
breakfast                        0
calories_chicken                 0
calories_day                    19
calories_scone                   1
coffee                           0
comfort_food                     1
comfort_food_reasons             2
comfort_food_reasons_coded      19
cook                             3
comfort_food_reasons_coded.1     0
cuisine                         17
diet_current                     1
diet_current_coded               0
drink                            2
eating_changes                   3
eating_changes_coded             0
eating_changes_coded1            0
eating_out                       0
employment                       9
ethnic_food                      0
exercise                        13
father_education                 1
father_profession                3
fav_cuisine                      2
fav_cuisine_coded                0
fav_food                         2
food_childhood                   1
fries                            0
fruit_day                        0
grade_level                      0
greek_food                       0
healthy_feeling                  0
healthy_meal                     1
ideal_diet                       1
ideal_diet_coded                 0
income                           1
indian_food                      0
italian_food                     0
life_rewarding                   1
marital_status                   1
meals_dinner_friend              3
mother_education                 3
mother_profession                2
nutritional_check                0
on_off_campus                    1
parents_cook                     0
pay_meal_out                     0
persian_food                     1
self_perception_weight           1
soup                             1
sports                           2
thai_food                        0
tortilla_calories                1
turkey_calories                  0
type_sports                     26
veggies_day                      0
vitamins                         0
waffle_calories                  0
weight                           2
dtype: int64

In [97]:
# 🚀 Extra credit: Try to display the NaN sums as a nice pandas DataFrame.
df_food.isna().sum().to_frame()

                               0
GPA                            2
Gender                         0
breakfast                      0
calories_chicken               0
calories_day                  19
calories_scone                 1
coffee                         0
comfort_food                   1
comfort_food_reasons           2
comfort_food_reasons_coded    19
cook                           3
comfort_food_reasons_coded.1   0
cuisine                       17
diet_current                   1
diet_current_coded             0
drink                          2
eating_changes                 3
eating_changes_coded           0
eating_changes_coded1          0
eating_out                     0
employment                     9
ethnic_food                    0
exercise                      13
father_education               1
father_profession              3
fav_cuisine                    2
fav_cuisine_coded              0
fav_food                       2
food_childhood                 1
fries                          0
fruit_day                      0
grade_level                    0
greek_food                     0
healthy_feeling                0
healthy_meal                   1
ideal_diet                     1
ideal_diet_coded               0
income                         1
indian_food                    0
italian_food                   0
life_rewarding                 1
marital_status                 1
meals_dinner_friend            3
mother_education               3
mother_profession              2
nutritional_check              0
on_off_campus                  1
parents_cook                   0
pay_meal_out                   0
persian_food                   1
self_perception_weight         1
soup                           1
sports                         2
thai_food                      0
tortilla_calories              1
turkey_calories                0
type_sports                   26
veggies_day                    0
vitamins                       0
waffle_calories                0
weight                         2

In [98]:
# 🚀 Extra credit: You can turn one line of code into multiple lines of code using a backslash as a continuation character to break up what would otherwise be a long line.
nan_counts = df_food.isna()\
    .sum()\
    .to_frame()

We gotta remove those `NaN`s―the entire row.

In [99]:
# Drop ‘em in-place.
df_food.dropna(inplace=True)

In [100]:
# 🚀 Extra credit: Check if the in-place modifications also affected the original DataFrame, df_food. 🙂
df_food.shape

(52, 61)

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [101]:
# Fix that in-place.
df_food['weight'] = pd.to_numeric(df_food['weight'], errors='coerce')

df_food.dropna(inplace=True)

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [102]:
# Savey save!

df_food.to_csv('data/food_coded_isclean.csv',index=False)

In [103]:
# 🚀 Extra credit: Load and print a few lines of the saved file as plain text.
with open('data/food_coded_isclean.csv') as file:
    for i in range(61):
        print(file.readline())

GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,cook,comfort_food_reasons_coded.1,cuisine,diet_current,diet_current_coded,drink,eating_changes,eating_changes_coded,eating_changes_coded1,eating_out,employment,ethnic_food,exercise,father_education,father_profession,fav_cuisine,fav_cuisine_coded,fav_food,food_childhood,fries,fruit_day,grade_level,greek_food,healthy_feeling,healthy_meal,ideal_diet,ideal_diet_coded,income,indian_food,italian_food,life_rewarding,marital_status,meals_dinner_friend,mother_education,mother_profession,nutritional_check,on_off_campus,parents_cook,pay_meal_out,persian_food,self_perception_weight,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight

3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,3.0,1,1.0,I eat about three times a day with some snacks. I try to eat healthy but it doesn't always work out that- sometimes eat fast food and mainly eat at Laker/ Egan ,2,2.0,I eat out more than usual. ,1,2,2,2.0,4,1.0,2.0,Self employed ,Italian,1,1.0,"chicken and biscuits, beef soup, baked beans",1,4,4,4,5,"Grains, Veggies, (more of grains and veggies), small protein and fruit with dairy ","Try to eat 5-6 small meals a day. While trying to properly distribute carbs, protein, fruits, veggies, and dairy.  ",3,4.0,4,4,1.0,2.0,"Pasta, steak, chicken ",4.0,Nurse RN ,4,1.0,1,4,4.0,3.0,1.0,1.0,2,725.0,690,Basketball ,4,2,900,155.0

3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips ","Stress, boredom, cravings ",1.0,1.0,1,2.0,I try to eat healthy but often struggle because of living on campus. I still try to keep the choices I do make balanced with fruits and vegetables and limit the sweats. ,2,2.0,I have eaten generally the same foods but I do find myself eating the same food frequently due to what I have found I like from egan and the laker. ,3,4,2,2.0,4,1.0,4.0,IT,Italian ,1,3.0,"Pasta, chicken tender, pizza ",1,4,4,4,6,"A lean protein such as grilled chicken, green vegetables and  brown rice or other whole grain ",Ideally I would like to be able to eat healthier foods in order to loose weight. ,2,6.0,2,5,1.0,1.0,"Chicken Parmesan, Pulled Pork, Spaghetti and meatballs ",5.0,Substance Abuse Conselor,3,1.0,1,4,2.0,4.0,1.0,1.0,4,940.0,500,Softball,4,2,760,190.0

3.8,2,1,610,3.0,420.0,2,"Chocolate, ice cream, french fries, pretzels","stress, boredom",1.0,2.0,1,1.0,"I eat a lot of chicken and broccoli for dinner, and usually tuna sandwiches for lunch.",3,1.0,I started eating a lot less and healthier because I wasn't playing sports year round anymore.,2,5,2,3.0,5,1.0,4.0,Assembler ,Thai,4,1.0,"grilled chicken, hamburgers",1,4,4,5,4,"Protein, vegetables, fruit, and some carbs","I would ideally like to eat more fresh fruits and vegetables. However, its difficult to get to the store all the time to buy fresh.",2,4.0,5,5,8.0,1.0,"Grilled chicken, steak, pizza",4.0,Journalist,4,2.0,2,2,5.0,4.0,1.0,1.0,5,940.0,690,soccer,4,1,1315,180.0

3.3,1,1,720,3.0,420.0,1,"Ice cream, cheeseburgers, chips.","I eat comfort food when im stressed out from school(finals week), when I`m sad, or when i am dealing with personal family issues.",1.0,3.0,1,1.0,"I eat a very healthy diet. Ocassionally, i will eat out and get unhealthy food.",1,2.0,"Freshmen year i ate very unhealthy, but now it is much healthier because of self control.",2,5,2,2.0,2,2.0,3.0,Business guy,Anything american style.,5,1.0,"chicken, cheesey potatoes, and hot dogs",1,5,2,3,3,A healthy meal has a piece of meat followed by a lot of fruit and veggies,My ideal diet is filled with a lot of fruit and chicken. I also really enjoy eggs any type of way with toast.,2,5.0,1,3,3.0,1.0,"chicken, steak, pasta ",2.0,cook,4,1.0,1,5,1.0,3.0,1.0,2.0,1,725.0,500,none,4,2,1315,137.0

3.3,1,1,430,3.0,315.0,2,"Mac and cheese, chocolate, and pasta ","Stress, anger and sadness ",1.0,3.0,1,1.0,"I eat healthy all the time when possible. I treat myself occasionally. I don't really like the greasy meals, if anything I would eat sweets over the greasy meals.  ",1,1.0,I cook a lot of my own foods back at home so not being able to cook my own healthy choices. I eat more carbs than normal when I'm at college due to the choices given in the cafe. ,1,3,3,3.0,5,1.0,5.0,commissioner of erie county ,Italian ,1,1.0,"Pasta, Eggs, Pancakes ",1,5,1,5,3,Chicken and rice with a side of veggies. ,"Lots of protein, carbs, and fruits and veggies. ",2,4.0,4,5,3.0,2.0,pasta salad and bread,5.0,Pharmaceutical rep,5,1.0,3,3,4.0,3.0,1.0,1.0,4,580.0,345,field hockey,5,1,900,125.0

3.5,1,1,610,3.0,980.0,2,"Pasta, grandma homemade chocolate cake anything homemade ",Boredom ,2.0,1.0,2,1.0,i eat very healthy. Maybe eat out 1-2 times a week.,1,2.0,Nun ,3,4,2,1.0,5,1.0,2.0,Idk,Orange chicken and chow mani noodles ,4,1.0,Chicken,1,5,3,1,9,"Chicken, and veggies ","Chicken, fish ",7,3.0,1,5,8.0,1.0,"chicken al king, spaghetti, fish",4.0,Chidos Cleaners,2,3.0,1,2,2.0,1.0,1.0,1.0,2,940.0,345,soccer,5,2,900,116.0

3.904,1,1,720,4.0,420.0,2,"chocolate, pasta, soup, chips, popcorn","sadness, stress, cold weather",3.0,3.0,3,1.0,"I am very health concious. I eat many fruits, veggies, and protiens. ",1,1.0,Less meat. ,4,5,1,2.0,5,1.0,3.0,Home Marker ,Italian,1,1.0,Scalloped potatoes and ham ,1,5,2,5,1,"lean protein, veggies, fruit, complex carbs",More healthy varienty. ,2,5.0,5,5,1.0,2.0,"Chicken parm, Fish, Pasta dishes ",4.0,Court Reporter ,5,1.0,1,3,5.0,2.0,1.0,1.0,5,940.0,500,Running,5,1,900,110.0

3.4,2,1,430,3.0,420.0,2,"Cookies, popcorn, and chips","Sadness, boredom, late night snack ",3.0,5.0,3,1.0,I focus mostly on proteins and fruits. I eat a lot less vegetables and a few carbohydrates.,1,2.0,I have been eating a lot more salads and soups.,2,5,1,3.0,4,3.0,3.0,Shirt designer ,Chinese ,4,3.0,"Pizza, chicken wings, and corn on the cob ",1,4,1,3,9,A salad with a reasonable amount of dressing and a meat.,My ideal diet would be the proper portions of all food categories. I would also like to eat proteins around my workouts and avoid all deserts.,1,5.0,3,4,9.0,2.0,"Cereal, pizza, toast ",4.0,Child care provider ,2,1.0,2,2,3.0,5.0,2.0,1.0,3,940.0,500,Soccer and basketball ,3,2,575,264.0

3.6,1,1,610,3.0,420.0,2,"ice cream, cake, chocolate","stress,  boredom, special occasions",1.0,2.0,1,1.0,Not as healthy when I am at school compared to home. Still very aware of the nutrition I am taking in.,2,2.0,not as healthy because healthy food goes bad quickly and it is expensive,1,3,4,2.0,5,2.0,2.0,business owner,italian,1,1.0,"steak, lasagna, crab",1,5,3,4,8,Lots of vegetabls with some grains like rice. Also has lean meat such as fish or chicken.,organic/healthy. fruits and vegetables but still protein to give sustainance. ,2,5.0,3,5,10.0,2.0,"pasta, chicken, steak",4.0,business owner,2,2.0,2,3,3.0,3.0,1.0,1.0,5,1165.0,850,intramural volleyball,5,2,1315,123.0

3.1,2,1,610,3.0,420.0,2,"Pizza, fruit, spaghetti, chicken and Potatoes  ","Friends, environment and boredom",2.0,3.0,2,1.0,"Making sure I have enough protein intake, as well with fibre, vitamins and carbs. ",1,2.0,"I knew I would eat alot my freshmen year, before coming to college i had a diet plan. ",3,4,2,3.0,4,2.0,4.0,Commidity trader ,Chinese ,4,3.0,Pizza,1,5,3,4,2,Green and not greasy,"Eat a little less than I usually do, and intaking more protein. ",1,5.0,2,3,1.0,1.0,"Pizza, chicken and rice, roast beef.",4.0,Charity worker,2,2.0,2,3,1.0,3.0,1.0,1.0,4,940.0,500,Hockey,5,1,900,185.0

3.6,2,1,430,3.0,980.0,2,"chips, cookies, ice cream","I usually only eat comfort food when I'm bored, if i am doing something, i can go for hours without eating ",2.0,3.0,2,1.0,My current diet is eggs and a meat every morning for breakfast. For lunch ill usually have some pasta or rice with a meat and sometimes a side of veggies. for dinner i usually eat less carbs and more protein and veggies. ,3,2.0,"I would say i just eat a little more, but not in a bad way. I have unlimited swipes at the cafe so instead of snacking on chips before lunch or dinner i will get something from the cafe.",1,2,2,3.0,4,1.0,2.0,self employed construction ,American or Italian ,5,3.0,"chicken fingers, steak, mac and cheese",1,3,1,3,8,"for me usually a big piece of chicken or steak with a side of veggies, and i usually have rice with mine as well","I like how my diet it now. However, after my season i am going to cut back on some carbs because i won't be working out as much.",1,6.0,3,5,7.0,2.0,Grilled chicken or steak with veggies and rice. or some type of pasta and chicken ,2.0,stay at home mom,4,1.0,1,6,2.0,2.0,1.0,1.0,3,940.0,500,hockey,4,2,900,170.0

3.4,1,1,720,3.0,980.0,1,"Chocolate, ice crea ","Sadness, stress",3.0,3.0,3,1.0,I eat lots of fruit and veggies. I eat lots of chicken.,1,1.0,I ate at the food hall.,4,6,3,2.0,1,3.0,5.0,Engineer,Chicken ,5,3.0,Chicken,1,5,2,3,6,Everything from food group ,Lots of fruit and veggies. Lots of chicken.,2,5.0,1,5,9.0,2.0,"Spaghetti, Chicken, Steak",3.0,Daycare provider,2,1.0,1,2,1.0,3.0,2.0,2.0,1,1165.0,690,dancing ,5,1,1315,135.0

3.3,2,1,610,3.0,980.0,2,"Fast food, pizza, subs","happiness, satisfaction",7.0,5.0,7,1.0,"I eat 2 meals a day, lunch and dinner",2,2.0,Late night food,1,3,4,2.0,4,1.0,5.0,CFO,Mexican,2,3.0,"pizza, chicken fingers",1,2,2,2,5,"Rice, Meat, vegetable",3 smaller meals a day,1,6.0,1,4,2.0,1.0,"Chicken, Pasta, Veal",4.0,Teacher,2,1.0,1,2,1.0,6.0,1.0,1.0,1,1165.0,850,Soccer,3,2,1315,175.0

3.7,2,1,610,3.0,420.0,1,"burgers, chips, cookies","sadness, depression ",3.0,5.0,3,2.0,balanced ,1,1.0,got worse ,1,3,1,2.0,3,1.0,4.0,accountant ,italian ,1,1.0,pasta,2,4,1,4,2,"pasta. veg, water ","fruit, veg and protien ",2,6.0,5,5,5.0,1.0,"pasta, pizza ",4.0,Underwiriter ,3,1.0,3,5,2.0,2.0,1.0,1.0,4,940.0,850,tennis soccer gym,3,1,1315,185.0

3.7,2,2,610,3.0,420.0,2,"Chilli, soup, pot pie",Stress and boredom ,1.0,4.0,1,1.0,2 meals a day. Rarely eat snacks. Fairly balanced diet. ,1,1.0,Drink coffee all the time. ,1,7,2,2.0,5,3.0,4.0,Commercial Real Estate,Asian ,4,1.0,Chicken Nuggets,1,3,3,2,4,"Protein, vegetables, grains ",3 healthy meals a day. No caffiene. ,1,4.0,4,5,5.0,1.0,"Pizza, Pasta, Poutine",2.0,Beautician ,2,1.0,2,3,2.0,3.0,1.0,1.0,4,940.0,690,Gaelic Football,4,1,1315,185.0

2.8,1,2,720,3.0,420.0,2,"chocolate, ice cream/milkshake, cookies",boredom,2.0,3.0,2,1.0,"vegetarian, eat breakfast some days before class, can eat a lot of junk food so I refrain from allowing myself to buy any",1,1.0,"none, I have dormed since high school",3,4,2,3.0,2,1.0,4.0,VP of ,don't have one,0,3.0,"Chicken parm, beef stroganof, tacos",1,4,1,3,8,"good portions, lots of color, targets main food groups","healthy, colorful, tasty, room for desserts",2,6.0,3,3,5.0,1.0,"Pasta

Take out",3.0,Medical biller,4,1.0,1,3,3.0,3.0,1.0,1.0,3,1165.0,690,Ice hockey,3,2,760,125.0

3.7,2,1,610,2.0,420.0,1,"Chips, ice cream, microwaveable foods ","Boredom, lazyniss ",2.0,3.0,2,1.0,"Most healthy diet, but since I'm an athlete have room for some bad foods to burn off quickly ",1,1.0,Tend to eat more fried foods ,1,3,2,2.0,2,1.0,4.0,Beverage and Food Sales,Italian food ,1,1.0,"Chicken Parm, Pizza ",1,3,2,1,9,"A rice, a vegetable, a piece of meat ","Very healthy diet, and to cook at home with organic foods. ",5,5.0,1,5,9.0,2.0,Chicken parm ,2.0,Doctors Billing Assiant ,2,1.0,1,4,1.0,2.0,2.0,1.0,2,1165.0,850,Hockey,3,2,1315,160.0

3,2,1,610,4.0,980.0,2,"Chicken fingers, pizza ",Boredom ,2.0,4.0,2,1.0,Very healthy. Good balance of proteins and vegetables ,1,2.0,A lot healthier ,2,5,2,3.0,3,1.0,5.0,Dentist ,Mexican ,2,1.0,Steak,1,5,1,3,9,"Salad, vegetable, carb, protein ",My current diet,6,6.0,3,4,9.0,2.0,"Steak, lobster, chicken ",5.0,Dentist ,4,1.0,1,6,2.0,2.0,1.0,1.0,3,1165.0,500,Lacrosse ,5,1,1315,175.0

4,2,1,610,3.0,420.0,2,"chips and dip, pepsi, ","stres, boredom, and nighttime",1.0,2.0,1,1.0,"Diet consists of 3000-4000 calories a day well rounded from meats, vegetables, and fruit.",2,2.0,none,3,4,2,3.0,5,2.0,4.0,deceased,italian,1,1.0,chicken and biscuits,1,5,2,5,5,"4-6 ounces chicken or fish, side of potatoes, and green beans","diet of 1500-2000 calories of white meat, vegetables, and fruit that are all fresh and not processed",1,4.0,4,5,3.0,1.0,"Chicken, Steak, Pasta",2.0,management,4,4.0,1,3,3.0,4.0,2.0,2.0,4,940.0,690,none organized,5,1,1315,205.0

3.65,1,1,610,3.0,420.0,2,"french fries, chips, ice cream","boredom, stressed, sad",2.0,4.0,2,1.0,egan dining,2,1.0,poor,1,3,3,3.0,2,1.0,4.0,Vice President of a company,French,1,3.0,"hamburgers, chicken nuggets ",1,5,1,3,1,a lot of greens,healthy and protien,7,6.0,1,5,3.0,1.0,"pasta, lasagna, chicken ",4.0,stylist,4,1.0,5,4,1.0,2.0,1.0,1.0,3,940.0,345,softball,4,1,1315,150.0

3,1,1,610,2.0,420.0,2,"mac n cheese, peanut butter and banana sandwich, omelet",Boredom usually,2.0,1.0,2,1.0,"A lot of rice and veggies, eggs for breakfast, chicken is usually the only kind of meat I eat.",3,1.0,My diet is more limited just because of what I have time to make,1,3,2,3.0,2,1.0,4.0,Owns his own promotional company ,American or Italian,5,1.0,"chicken, pasta, stir fry",1,5,3,3,2,"Some kind of protein, a vegetable, and a grain",Pretty much what I eat now,6,4.0,1,5,3.0,2.0,"Some kind of pasta, a chicken dish, some kind of salad",4.0,Works in retail,2,2.0,1,3,2.0,2.0,1.0,1.0,2,940.0,690,Lacrosse,5,2,760,150.0

3.4,1,1,720,4.0,420.0,2,"chocolate, chips, candy",Stress,1.0,2.0,1,6.0,"I do not get to eat as well as I did.  I wish I ate better, but in college it is hard because of money.",2,2.0,I do not eat as many home cooked meals.,1,3,2,2.0,4,3.0,2.0,Construction ,Italian,1,1.0,Pasta,1,3,4,5,4,"A protein, starch, veg, and a healthier dessert. ",I would like to get all of the food groups in each day.  ,2,6.0,3,5,2.0,2.0,"Pasta, Pizza, Chicken ",3.0,Head of Human Resouces,4,1.0,1,4,3.0,4.0,1.0,1.0,5,940.0,500,Dancing,4,2,1315,170.0

3.89,1,1,610,3.0,980.0,2,"chocolate, popcorn, ice cream","boredom, stress",2.0,3.0,2,1.0,I eat three meals per day usually. I eat a lot of sandwiches and fruit.,1,1.0,I have eaten bigger meals.,1,2,2,3.0,4,2.0,4.0,Biohemical Waste Elimination,italian,1,1.0,chicken parmesan,1,4,4,3,6,a lean protein plus the addition of 2-3 fruits and vegetables,My ideal diet would be eating multiple fruits and vegetables at each meal. Also I would only eat lean protein if possible.,2,5.0,3,5,8.0,2.0,"Chicken Parmesan, Orange Chicken, Tacos",4.0,Accountant,4,1.0,1,3,3.0,4.0,1.0,1.0,2,1165.0,690,Lacrosse,3,2,1315,150.0

3.4,2,1,430,3.0,315.0,1,"Pizza, Ice cream, fries, cereal, cookies  ",Usually if I'm sad or depressed. ,3.0,3.0,3,1.0,"I will eat a full bleakest every morning consisting of eggs, potatoes, and a type of meat with juice. I will have a sandwich or something light for lunch. For dinner I will have meat and vegetables of some sort.  ",3,2.0,I eat pretty much the same as I use too. I do have more sweets now though. ,1,9,2,3.0,4,1.0,4.0,Small business owner ,Italian ,1,1.0,"pizza, ice cream. pop tarts ",1,3,1,5,10,A meal with all of the food groups. ,Idealy I would have basically the same breakfast as I do now just with more fruits. For lunch I would have more vegetables and fruits. For dinner I would have the same.   ,2,6.0,3,5,8.0,1.0,"Pizza, Japanize Hibachi, Moes   ",4.0,Middle school teacher,3,1.0,1,3,3.0,2.0,1.0,1.0,3,940.0,500,wrestling ,4,2,760,140.0

3.2,1,1,610,4.0,420.0,2,"Potato chips, ice cream, chocolate, cookies","Stress, boredom, craving",1.0,1.0,1,1.0,"I am on a very balanced diet, eating 4-5 small meals a day filled with fruits, vegetables, lean meat, and good carbs. ",1,1.0,"I haven't changed much. If anything, I have become more disciplined. ",2,4,2,2.0,5,1.0,4.0,Electrical Engineer,Thai food,4,1.0,"Mac and Cheese, Hot Dogs, Grilled Cheese",1,5,4,5,8,Mostly green!,"My ideal diet would be to be a vegetarian; however, considering my highly active lifestyle island strength requirement I need as much ""real"" protein I can get. ",7,5.0,5,5,10.0,1.0,"Steak, asparagus and potatoes, homemade chicken alfredo, Mexican cuisine",2.0,Secretary,4,2.0,1,6,5.0,3.0,1.0,1.0,5,725.0,500,Volleyball,5,1,760,170.0

3.8,2,1,430,2.0,420.0,1,"popcorn, chips, candy, & fries ","sadness, boredom, & anger ",3.0,3.0,3,1.0,At school I eat a lot of pizza or burgers with fries. Occasionally I try to have a salad or a fruit juice with this. I also try to eat more of a home cooked meal with vegetables.,2,2.0,Eating more pizza and burgers or fast food.  ,1,2,2,2.0,4,2.0,3.0,subcontractor ,Italian ,1,1.0,"chicken soup,  perogies, & roast beef  ",1,4,1,4,4,A meal that you have cooked yourself without a lot of grease or fat in it.  ,More of a home cooked meal that is not very greasy. Also includes more fruits and vegetables. ,5,4.0,3,5,4.0,1.0,"Spaghetti, steak, burgers ",4.0,telemarketer ,3,1.0,2,3,3.0,3.0,1.0,1.0,3,725.0,345,soccer ,4,2,900,168.0

3.3,2,1,610,4.0,980.0,1,Burger,Lazy,5.0,3.0,5,1.0,Great ,4,1.0,Mediocre ,1,3,3,3.0,5,1.0,2.0,President of Automotive company ,All ,0,1.0,Steak ,1,5,2,5,8,Chicken ,Organic ,5,6.0,5,5,8.0,1.0,"Steak, Chicken, Pasta ",2.0,Stay home,5,1.0,1,3,5.0,2.0,1.0,1.0,5,1165.0,500,Hockey,4,1,1315,185.0

3.5,2,1,610,3.0,420.0,2,"peanut butter sandwich, pretzals, garlic bread","stress, anger and boredom",1.0,1.0,1,2.0,Very healthy and clean. A lot of protein and vegetables,1,1.0,I eat a lot more healthier,2,5,3,3.0,5,1.0,4.0,Sergeant correctional officer,Italian,1,1.0,Chicken Alfredo,2,5,2,5,10,High protein and vegetables,Clean diet. High protein intake.,7,6.0,4,5,10.0,1.0,"Chicken, Steak, Pasta",5.0,Teacher,4,1.0,1,6,2.0,2.0,1.0,1.0,4,940.0,690,hockey,5,1,900,165.0

3.8,2,1,720,4.0,315.0,2,"Pizza, Ice Cream, Chicken Wings",I usually only eat comfort foods when I am bored. I will also eat them when I am happy to celebrate and then when I am sad to comfort me.,2.0,3.0,2,1.0,I usually eat very healthy. I incorporate fresh fruits and vegetables into every meal.,1,1.0,I have begun to eat more fruits and vegetables because I have been more aware of my physique.,2,5,4,3.0,5,1.0,4.0,Salesman,Thai,4,1.0,Meatloaf,1,5,4,4,1,Low protein and carbs and high in vegetables and fruits.,My ideal diet is to cut back on my meat intake and substitute it for other protein sources such as fish or tuna.,2,6.0,5,5,1.0,1.0,"Chicken, Beef, Steak",4.0,Nurse,4,2.0,1,4,4.0,2.0,1.0,1.0,5,1165.0,500,Hockey,5,1,1315,175.0

2.8,1,1,610,4.0,980.0,2,Pizza chocolate chips bagels ice Capps ,Just cause ,9.0,2.0,9,1.0,I eat very heathy on a daily basis ,1,1.0,Really paid more attention to what I eat cause it is easy to gain ,2,5,3,2.0,2,1.0,2.0,Owns his business,Wraps ,5,3.0,Pizza pasta and quesadillas ,2,4,2,5,9,Chicken and broccoli ,"Fruits and vegetables, wheat bread, peanut butter, protein bars, protein shakes ",2,5.0,2,5,10.0,1.0,"chicken, pizza, stuffed shells",4.0,Sales,5,1.0,1,3,1.0,2.0,2.0,1.0,2,725.0,345,softball,4,1,1315,140.0

3.5,1,1,610,3.0,420.0,2,"Chocolate, ice cream, pasta","Stress, boredom, sadness",1.0,1.0,1,2.0,"For breakfast I have oatmeal. For lunch I have a sandwich and fruit. For dinner I usually have a piece of meat, rice or pasta, and a vegetable. ",3,2.0,More easy meals like pasta.,1,11,2,2.0,5,2.0,4.0,Physical Therapist,Mexican,2,1.0,Steak,2,5,3,5,4,"Fruit, vegetables, and protien",Ideally my diet would be similar to what I eat now. If I wasn't on a college budget I could spend more money on nicer meat and vegetables which would make my meals a lot better.,6,5.0,5,5,1.0,1.0,"steak, noodles, edemame",5.0,Elementary School Principal,2,2.0,1,4,4.0,3.0,1.0,1.0,5,1165.0,690,Skiing,5,1,1315,155.0


## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

Load the Ask A Manager Salary Survey 2021 (Responses) data set into a new variable, `df_salary`.

In [105]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set.
df_salary = pd.read_csv('data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv', sep='\t')

Was that hard? 🙃

### Explore

You know the drill.

How much data did you just load?

In [106]:
# Count by hand. I’m dead serious.
df_salary.shape

(28062, 18)

What are the columns and their types?

In [108]:
# Show the column names and their types.
df_salary.info()

<class 'pandas.DataFrame'>
RangeIndex: 28062 entries, 0 to 28061
Data columns (total 18 columns):
 #   Column                                                                                                                                                                                                                                Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                --------------  -----
 0   Timestamp                                                                                                                                                                                                                             28062 non-null  str
 1   How old are you?                                                                                                                                                                                                                      28062 non-null  str
 2   What industry do you work in?                                                                                                                                                                                                         27988 non-null  str
 3   Job title                                                                                                                                                                                                                             28061 non-null  str
 4   If your job title needs additional context, please clarify here:                                                                                                                                                                      7262 non-null   str
 5   What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)  28062 non-null  str
 6   How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                        20766 non-null  float64
 7   Please indicate the currency                                                                                                                                                                                                          28062 non-null  str
 8   If "Other," please indicate the currency here:                                                                                                                                                                                        206 non-null    str
 9   If your income needs additional context, please provide it here:                                                                                                                                                                      3042 non-null   str
 10  What country do you work in?                                                                                                                                                                                                          28062 non-null  str
 11  If you're in the U.S., what state do you work in?                                                                                                                                                                                     23039 non-null  str
 12  What city do you work in?                                                                                                                                                                                                             27980 non-null  str
 13  How many years of professional work experience do you have overall?                                                                                                                                                                   28062 non-null  str
 14  How many years of professional work experience do you have in your field?                                                                                                                                                             28062 non-null  str
 15  What is your highest level of education completed?                                                                                                                                                                                    27840 non-null  str
 16  What is your gender?                                                                                                                                                                                                                  27891 non-null  str
 17  What is your race? (Choose all that apply.)                                                                                                                                                                                           27885 non-null  str
dtypes: float64(1), str(17)
memory usage: 3.9 MB

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [109]:
# Rename ‘em in-place.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race
df_salary.columns = ['timestamp', 'age', 'industry', 'title', 'title_context', 'salary',
                      'additional_compensation', 'currency', 'other_currency', 'salary_context',
                      'country', 'state', 'city', 'total_yoe', 'field_yoe',
                      'highest_education_completed', 'gender', 'race']

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [110]:
# List the unique industries and a count of their instances.
df_salary['industry'].value_counts()

industry
Computing or Tech                               4699
Education (Higher Education)                    2464
Nonprofits                                      2419
Health care                                     1896
Government and Public Administration            1889
                                                ...
Undergrad student                                  1
Concrete Construction                              1
I'm currently a student and don't have a job       1
Student                                            1
Wine & Spirits                                     1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new variable, `df_salary_tech`.

In [111]:
# Filtery filter.
df_salary_tech = df_salary[df_salary['industry'] == 'Computing or Tech']

Do a sanity check by counting.

In [112]:
# Sanity check count.
df_salary_tech.shape

(4699, 18)

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [113]:
# Filtery filter (in place) for just the jobs that pay in USD!
df_salary_tech = df_salary_tech[df_salary_tech['currency'] == 'USD']

What we really want know is how each U.S. state pays in tech. What value in `country` represents the United States of America?

In [114]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.
df_salary_tech['country'].value_counts()

country
United States                1576
USA                          1222
US                            412
U.S.                          108
United States of America       90
United States                  68
Usa                            59
USA                            56
usa                            28
United states                  23
united states                  14
Us                             12
us                              9
U.S.A.                          7
United States of America        7
Israel                          5
Canada                          4
U.S.                            2
United State of America         2
Unite States                    2
Australia                       2
UnitedStates                    2
India                           2
U.S                             2
Usa                             2
United States Of America        2
Spain                           2
Brazil                          2
United Kingdom                  2
united States                   2
New Zealand                     2
Poland                          2
France                          2
U.S.A                           2
United States of america        2
US                              1
Uniyed states                   1
America                         1
Puerto Rico                     1
U.s.                            1
 US                             1
United State                    1
Cuba                            1
Danmark                         1
Italy                           1
International                   1
United Stated                   1
Remote (philippines)            1
Singapore                       1
Uruguay                         1
Mexico                          1
Canada                          1
United Stateds                  1
ISA                             1
singapore                       1
Pakistan                        1
Netherlands                     1
China                           1
San Francisco                   1
Romania                         1
United STates                   1
Japan                           1
United Stares                   1
Australian                      1
Denmark                         1
Jamaica                         1
Unites States                   1
Thailand                        1
U.S.A                           1
Colombia                        1
denmark                         1
Ghana                           1
Nigeria                         1
ss                              1
Nigeria                         1
Burma                           1
Name: count, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [115]:
# Replace them all in-place with 'US'.
us_variants = df_salary_tech['country'].value_counts().head(5).index.tolist()
df_salary_tech['country'] = df_salary_tech['country'].replace(us_variants, 'US')

Have a look at the count of each unique country again now.

In [116]:
# Count again.
df_salary_tech['country'].value_counts()

country
US                           3408
United States                  68
Usa                            59
USA                            56
usa                            28
United states                  23
united states                  14
Us                             12
us                              9
U.S.A.                          7
United States of America        7
Israel                          5
Canada                          4
U.S.                            2
United State of America         2
Unite States                    2
Australia                       2
UnitedStates                    2
India                           2
U.S                             2
Usa                             2
United States Of America        2
Spain                           2
Brazil                          2
United Kingdom                  2
united States                   2
New Zealand                     2
Poland                          2
France                          2
U.S.A                           2
United States of america        2
US                              1
Uniyed states                   1
America                         1
Puerto Rico                     1
U.s.                            1
 US                             1
United State                    1
Cuba                            1
Danmark                         1
Italy                           1
International                   1
United Stated                   1
Remote (philippines)            1
Singapore                       1
Uruguay                         1
Mexico                          1
Canada                          1
United Stateds                  1
ISA                             1
singapore                       1
Pakistan                        1
Netherlands                     1
China                           1
San Francisco                   1
Romania                         1
United STates                   1
Japan                           1
United Stares                   1
Australian                      1
Denmark                         1
Jamaica                         1
Unites States                   1
Thailand                        1
U.S.A                           1
Colombia                        1
denmark                         1
Ghana                           1
Nigeria                         1
ss                              1
Nigeria                         1
Burma                           1
Name: count, dtype: int64

Did you notice anything interesting?

In [130]:
# 🚀 Extra credit: Resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.
us_variants = df_salary_tech['country'].value_counts().head(5).index.tolist()
df_salary_tech['country'] = df_salary_tech['country'].replace(us_variants, 'US')

In [131]:

# 🚀 Extra credit: If you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.
df_salary_tech['country'].value_counts()

country
US                          3732
U.S.A                          2
United States of america       2
US                             1
Uniyed states                  1
America                        1
Puerto Rico                    1
U.s.                           1
 US                            1
United State                   1
Cuba                           1
Danmark                        1
Italy                          1
International                  1
United Stated                  1
Remote (philippines)           1
Singapore                      1
Uruguay                        1
Mexico                         1
Canada                         1
United Stateds                 1
ISA                            1
singapore                      1
Pakistan                       1
Netherlands                    1
China                          1
San Francisco                  1
Romania                        1
United STates                  1
Japan                          1
United Stares                  1
Australian                     1
Denmark                        1
Jamaica                        1
Unites States                  1
Thailand                       1
U.S.A                          1
Colombia                       1
denmark                        1
Ghana                          1
Nigeria                        1
ss                             1
Nigeria                        1
Burma                          1
Name: count, dtype: int64

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [137]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.
df_salary_tech.groupby('state')['salary'].agg(['min', 'mean', 'max']).sort_values('mean', ascending=False)

                                   min           mean      max
state
Michigan, Texas, Washington     340000  340000.000000   340000
California, Oregon              200000  200000.000000   200000
California, Colorado            176000  176000.000000   176000
Georgia, Massachusetts          175000  175000.000000   175000
Florida                          28800  157457.232143  2600000
Alabama, District of Columbia   156000  156000.000000   156000
California                           0  154857.215478   875000
Washington                          72  151423.670588   950000
New York                         14000  148054.638968   590000
Nevada                           38000  141310.000000   425000
New Jersey, New York            135000  137500.000000   140000
Massachusetts                    37000  135213.537954  1650000
District of Columbia             10000  132318.036364   267500
New Mexico                       70000  132200.000000   300000
Utah, Vermont                   130000  130000.000000   130000
New Jersey                       40000  128802.475000   603000
Connecticut                      62400  128375.000000   270000
Virginia                         43642  127706.355932   450000
Colorado                         45000  127240.006849   630000
Massachusetts, Rhode Island     125000  125000.000000   125000
Oregon                           16200  124297.800000   320000
Georgia, Washington             123000  123000.000000   123000
West Virginia                   116500  120500.000000   125000
Illinois                         13500  119268.242604   315000
Georgia                          29120  117893.098765   250000
Maryland                         51260  117862.370370   205000
Louisiana, Washington           117000  117000.000000   117000
Delaware                         63000  116600.000000   169000
South Dakota                     86000  115333.333333   150000
Wisconsin                            1  114268.000000   920000
Texas                            10700  113909.713004   280000
Tennessee                        36550  112847.058824   240000
Alaska                           67000  112500.000000   158000
Vermont                          65000  111781.250000   200000
Pennsylvania                     32000  111623.123894   237000
Idaho                            50000  111527.692308   312000
Rhode Island                     76000  111491.666667   180000
District of Columbia, Virginia  109200  109200.000000   109200
Minnesota                        34000  106752.793103   230000
Ohio                             32240  106338.835821   954000
Utah                             33280  105836.479167   245000
North Carolina                   29000  105035.441441   260000
New York, Texas                 105000  105000.000000   105000
Massachusetts, New Hampshire    105000  105000.000000   105000
Arizona                          35000  104491.891892   210000
Maine                            50000  103571.428571   173000
South Carolina                   40000  102111.111111   205000
Iowa                             47840   99729.736842   160000
Kansas                           41500   99565.052632   167000
North Dakota                     45760   97880.000000   150000
Michigan                         36800   96855.363636   235000
Montana                          65000   95500.000000   145000
Missouri                            80   95317.652174   200000
New Hampshire                       55   95179.705882   193000
Arizona, Utah                    95000   95000.000000    95000
Mississippi                      94000   94000.000000    94000
Alabama                          29120   92510.000000   350000
Kentucky                         39000   92375.000000   170000
Nebraska                         43000   90975.294118   166400
Indiana                          15000   88566.647059   200000
Oklahoma                         28536   87929.500000   180000
Louisiana                        35360   83269.090909   150000
Massachusetts, Pennsylvania      83000   83000.000000    83000
California, Maryland             81500   81500.000000    81500
Arkansas                             4   74257.000000   144000
Alabama, Montana                 72000   72000.000000    72000

 Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed. 🤔

In [138]:
# Fix it in-place.
df_salary_tech['salary'] = pd.to_numeric(df_salary_tech['salary'].str.replace(',', ''), errors='coerce')

AttributeError: Can only use .str accessor with string values, not integer

Let’s try that again.

In [139]:
# Try it again. Yeah!
df_salary_tech.groupby('state')['salary'].agg(['min', 'mean', 'max']).sort_values('mean', ascending=False)

                                   min           mean      max
state
Michigan, Texas, Washington     340000  340000.000000   340000
California, Oregon              200000  200000.000000   200000
California, Colorado            176000  176000.000000   176000
Georgia, Massachusetts          175000  175000.000000   175000
Florida                          28800  157457.232143  2600000
Alabama, District of Columbia   156000  156000.000000   156000
California                           0  154857.215478   875000
Washington                          72  151423.670588   950000
New York                         14000  148054.638968   590000
Nevada                           38000  141310.000000   425000
New Jersey, New York            135000  137500.000000   140000
Massachusetts                    37000  135213.537954  1650000
District of Columbia             10000  132318.036364   267500
New Mexico                       70000  132200.000000   300000
Utah, Vermont                   130000  130000.000000   130000
New Jersey                       40000  128802.475000   603000
Connecticut                      62400  128375.000000   270000
Virginia                         43642  127706.355932   450000
Colorado                         45000  127240.006849   630000
Massachusetts, Rhode Island     125000  125000.000000   125000
Oregon                           16200  124297.800000   320000
Georgia, Washington             123000  123000.000000   123000
West Virginia                   116500  120500.000000   125000
Illinois                         13500  119268.242604   315000
Georgia                          29120  117893.098765   250000
Maryland                         51260  117862.370370   205000
Louisiana, Washington           117000  117000.000000   117000
Delaware                         63000  116600.000000   169000
South Dakota                     86000  115333.333333   150000
Wisconsin                            1  114268.000000   920000
Texas                            10700  113909.713004   280000
Tennessee                        36550  112847.058824   240000
Alaska                           67000  112500.000000   158000
Vermont                          65000  111781.250000   200000
Pennsylvania                     32000  111623.123894   237000
Idaho                            50000  111527.692308   312000
Rhode Island                     76000  111491.666667   180000
District of Columbia, Virginia  109200  109200.000000   109200
Minnesota                        34000  106752.793103   230000
Ohio                             32240  106338.835821   954000
Utah                             33280  105836.479167   245000
North Carolina                   29000  105035.441441   260000
New York, Texas                 105000  105000.000000   105000
Massachusetts, New Hampshire    105000  105000.000000   105000
Arizona                          35000  104491.891892   210000
Maine                            50000  103571.428571   173000
South Carolina                   40000  102111.111111   205000
Iowa                             47840   99729.736842   160000
Kansas                           41500   99565.052632   167000
North Dakota                     45760   97880.000000   150000
Michigan                         36800   96855.363636   235000
Montana                          65000   95500.000000   145000
Missouri                            80   95317.652174   200000
New Hampshire                       55   95179.705882   193000
Arizona, Utah                    95000   95000.000000    95000
Mississippi                      94000   94000.000000    94000
Alabama                          29120   92510.000000   350000
Kentucky                         39000   92375.000000   170000
Nebraska                         43000   90975.294118   166400
Indiana                          15000   88566.647059   200000
Oklahoma                         28536   87929.500000   180000
Louisiana                        35360   83269.090909   150000
Massachusetts, Pennsylvania      83000   83000.000000    83000
California, Maryland             81500   81500.000000    81500
Arkansas                             4   74257.000000   144000
Alabama, Montana                 72000   72000.000000    72000

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [140]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.
df_salary_tech_recent = df_salary_tech[
    df_salary_tech['timestamp'].str.startswith(('2021', '2022', '2023'))
]

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)